<a href="https://colab.research.google.com/github/jsgovea/PyTorch-learning/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PyTorch fundamentals

In [30]:
import torch

print(torch.__version__)

2.1.0+cu118


## Introduction to Tensors

### Creating tensors

In [31]:
# scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [32]:
scalar.ndim

0

In [33]:
# Get tensor back as Python int
scalar.item()

7

In [34]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [35]:
vector.ndim

1

In [36]:
vector.shape

torch.Size([2])

In [37]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [38]:
MATRIX.ndim

2

In [39]:
MATRIX[1]

tensor([ 9, 10])

In [40]:
MATRIX.shape

torch.Size([2, 2])

In [41]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [42]:
TENSOR.ndim

3

In [43]:
TENSOR.shape

torch.Size([1, 3, 3])

In [44]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

