<a href="https://colab.research.google.com/github/jsgovea/PyTorch-learning/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PyTorch fundamentals

In [105]:
import torch

print(torch.__version__)

2.1.0+cu118


## Introduction to Tensors

### Creating tensors

In [106]:
# scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [107]:
scalar.ndim

0

In [108]:
# Get tensor back as Python int
scalar.item()

7

In [109]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [110]:
vector.ndim

1

In [111]:
vector.shape

torch.Size([2])

In [112]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [113]:
MATRIX.ndim

2

In [114]:
MATRIX[1]

tensor([ 9, 10])

In [115]:
MATRIX.shape

torch.Size([2, 2])

In [116]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [117]:
TENSOR.ndim

3

In [118]:
TENSOR.shape

torch.Size([1, 3, 3])

In [119]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [120]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2089, 0.6403, 0.7636, 0.5325],
        [0.2051, 0.1463, 0.3513, 0.9039],
        [0.3780, 0.4808, 0.8428, 0.6691]])

In [121]:
random_tensor.ndim

2

In [122]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([3, 224, 224]), 3)

In [123]:
# More random tensors
another_tensor = torch.rand(10, 10, 10)
random_tensor.shape

torch.Size([3, 4])

## Zeros and *ones*

In [124]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [125]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [126]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [127]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [128]:
# Create tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors with pytorch & deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

__Precision in computing__

In [129]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What datatype is the tensor (e.g float32 or float16)
                               device=None, # What device is your tensor on
                               requires_grad=False) # Wheter or not to track gradients  witht his tensors operations
float_32_tensor.dtype

torch.float32

In [130]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [131]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [132]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get a shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [133]:
 # Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6999, 0.5011, 0.9419, 0.4018],
        [0.4354, 0.4753, 0.9457, 0.6710],
        [0.6308, 0.9846, 0.4102, 0.9622]])

In [134]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of dtype: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")


tensor([[0.6999, 0.5011, 0.9419, 0.4018],
        [0.4354, 0.4753, 0.9457, 0.6710],
        [0.6308, 0.9846, 0.4102, 0.9622]])
Datatype of dtype: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating tensors (tensor operations)

Tensor operations include:
* Addition
* Substraction
* Multuplication (element-wise)
* Division
* Matrix multiplication

In [135]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [136]:
# Multiply tensor by 10
tensor * 10


tensor([10, 20, 30])

In [137]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [138]:
# Try out pytorch in-built functions
torch.mul(tensor, 10)
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matriz multiplication

Two main ways of performing multiplication in neural networks and deep learning

1. Element-wise multiplication
2. Matriz multiplication (dot produ ct)

In [139]:
# Element wise multiplication
print(tensor, '*', tensor)
print(f"Equal: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equal: tensor([1, 4, 9])


In [140]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [141]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [142]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.61 ms, sys: 0 ns, total: 1.61 ms
Wall time: 1.63 ms


In [143]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 293 µs, sys: 0 ns, total: 293 µs
Wall time: 298 µs


tensor(14)

### One of the most common errors in deep learning: shape errors