<a href="https://colab.research.google.com/github/jsgovea/PyTorch-learning/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PyTorch fundamentals

In [7]:
import torch

print(torch.__version__)

2.1.0+cu118


## Introduction to Tensors

### Creating tensors

In [9]:
# scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [10]:
scalar.ndim

0

In [11]:
# Get tensor back as Python int
scalar.item()

7

In [15]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7, 7])

In [16]:
vector.ndim

1

In [17]:
vector.shape

torch.Size([3])

In [18]:
# Matrix
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [19]:
matrix.ndim

2

In [21]:
matrix[1]

tensor([ 9, 10])

In [22]:
matrix.shape

torch.Size([2, 2])

In [28]:
# Tensor
tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5],
         [5, 5, 5]]])

In [29]:
tensor.ndim

3

In [26]:
tensor.shape

torch.Size([1, 3, 3])

In [27]:
tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])